### PR TITLE
Move example to deployments and add help for monitor tests in readme

### PR DESCRIPTION
**Pull request by waseem-h**

### CODE REVIEW

**Comment by rasheedamir** [comment]
@waseem-h why is it waiting forever to start? Might be the jenkins slave is failing to startup due to missing secrets or something?

**Comment by waseem-h** [comment]
@rasheedamir we restarted jenkins to test something. It should be up and start running these jobs

**Comment by stakater-user** [comment]
@waseem-h Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.tools.stackator.com/job/Stakater/job/IngressMonitorController/job/PR-86/1/) has Failed!

**Comment by hazim1093** [comment]
@rasheedamir we added statusCake config in the test config we have in jenkins, for #76 to be able to build. 
So these PRs would not work as the code in the PR knows nothing about statusCake

**Pull request merged**
