### PR TITLE
[dev:Stage] Adding resources for kube-rbac-proxy in imc

### PR DESCRIPTION
**Pull request by Muneebstakater**

### CODE REVIEW

**Comment by stakater-user** [comment]
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/03b6570250f913addf40a8ded9ea0d72f2017083/checks) has Failed!

**Comment by stakater-user** [comment]
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/016cdd920273d728192a926bc3ad0e45470dd4cc/checks) has Failed!

**Comment by stakater-user** [comment]
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/b106266e839b226ee20cb47c1472c0bc4f66a655/checks) has Failed!

**Comment by Muneebstakater** [comment]
Closing this PR as this is not required

**Pull request closed without merging**
