### PR TITLE
Adding README with default values

### LINKED ISSUE #224: Add Helm chart's configuration and parameters table
Previously IMC was hosted on public stable helm repo, but as that is being deprecated so moving to Stakater's repository, so we need to add chart's configuration and parameters table in this repo as well like in the stable chart's repo with updated configuration

https://github.com/helm/charts/tree/master/stable/ingressmonitorcontroller#usage

### PR DESCRIPTION
**Pull request by jseiser**
Fixes #224 

Adds a basic read-me documenting the chart options.

### CODE REVIEW

**Comment by stakater-user** [comment]
@jseiser Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-225/1/) has Failed!

**Comment by rasheedamir** [comment]
@jseiser can you please update the branch so, that we can merge it?

**Comment by stakater-user** [comment]
@jseiser Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-225/2/) has Failed!

**Comment by stakater-user** [comment]
@jseiser Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-225-3``

**Comment by stakater-user** [comment]
@jseiser Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-225-4``

**Comment by stakater-user** [comment]
@jseiser Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-225-2``

**Pull request merged**
