### PR TITLE
IMC pingdom api v3.1 support with small improvements and documentation fixes

### PR DESCRIPTION
**Pull request by artemlive**

### CODE REVIEW

**Comment by stakater-user** [comment]
@artemlive Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins-delivery.stakater.com/job/Stakater/job/IngressMonitorController/job/PR-287/1/) has Failed!

**Comment by stakater-user** [comment]
@artemlive Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-287-2``

**Comment by stakater-user** [comment]
@artemlive Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins-delivery.stakater.com/job/Stakater/job/IngressMonitorController/job/PR-287/3/) has Failed!

**Comment by stakater-user** [comment]
@artemlive Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-287-5``

**Review by ahmedwaleedmalik — COMMENTED** [review]
LGTM

@artemlive can you please perform these steps as well to update the image and resources to `v2.0.5` ? For the time being it's a manual step. 

https://github.com/stakater/IngressMonitorController/blob/master/CONTRIBUTING.md#creating-a-new-release

**Comment by artemlive** [comment]
> LGTM
> 
> @artemlive can you please perform these steps as well to update the image and resources to `v2.0.5` ? For the time being it's a manual step.
> 
> https://github.com/stakater/IngressMonitorController/blob/master/CONTRIBUTING.md#creating-a-new-release

@ahmedwaleedmalik thanks for your reply, I made the changes as you requested.

**Comment by stakater-user** [comment]
@artemlive Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-287-6``

**Review by ahmedwaleedmalik — APPROVED** [review]
LGTM

**Pull request merged**
