### PR TITLE
Additional Statuscake annotations

### PR DESCRIPTION
**Pull request by Ferlonas**
I added the requested unittests to PR proposed by @thoo5ieb (https://github.com/stakater/IngressMonitorController/pull/204) and adapted the code according to what they revealed (two lines changed)

### CODE REVIEW

**Comment by Ferlonas** [comment]
What do you require from me so this can be reviewed?

**Comment by stakater-user** [comment]
@Ferlonas Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-218/2/) has Failed!

**Comment by stakater-user** [comment]
@Ferlonas Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-218-3``

**Comment by rasheedamir** [comment]
@Ferlonas it should be merged early next week; thanks for the patience; team has been occupied

**Comment by GeorgFleig** [comment]
Would love to see this PR merged! Without it, orchestrating StatusCake alerts is basically not possible without manual setting of the currently unsupported fields. Is there any progress on the review/merge?

**Comment by stakater-user** [comment]
@GeorgFleig @Ferlonas I will look into this today, actually the team is pretty occupied these days.

**Comment by stakater-user** [comment]
@Ferlonas Yikes! You better fix it before anyone else finds out! [Build 8](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-218/8/) has Failed!

**Comment by stakater-user** [comment]
@Ferlonas Yikes! You better fix it before anyone else finds out! [Build 9](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-218/9/) has Failed!

**Comment by stakater-user** [comment]
@Ferlonas Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-218-10``

**Pull request merged**
