### PR TITLE
Bump operator sdk v1.6.2

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
This PR will upgrade operator from using `operator-sdk` v0.18 to v1.6.2.

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/033728b8ee17fb7efaa727b43389b3fe1174fe71/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/7ec8dbe5d527eb915c34030ecf1b82b0eb90483b/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/8d2f53b3b56a35ef095f910c28687ec8aaa2869c/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/3a9c2ec075c0d2e10b7873a1de57d87982409bc7/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/db27fe2dff7492773922ee23a6e3dab757447679/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/1daa52f8732ed696900b95061806dc9c8fd82e62/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/33b82163aa3f8d05f38f86559eb37c2a7750f631/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/f709a24f06f300d1a06edb5d02a59d04dc7578fb/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/3a4bfb107b73ec5f8783ab40ebfe08c4fa244db0/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/3742ea1f1aa1602fcbfcf502d70d67f05bebed0d/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/ad37207ebfef14c135fe8ee839a3c16c1472e0c5/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/14f419fde1dbfb808f71a18abdfe7598e23e50c2/checks) has Failed!

**Review by abdulhaseeb2 — APPROVED** [review]
LGTM

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/9ec1af6204820daa37e0936e5898f2ad82d67d9d/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/IngressMonitorController:SNAPSHOT-PR-317-1d54311f`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/8b008d7fe729685384af3f791f5436cb8cf62726/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/30190f9270fbd8f2058865253f2db9bbc83bd43a/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/IngressMonitorController:SNAPSHOT-PR-317-3b3cdd06`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/IngressMonitorController:SNAPSHOT-PR-317-2743e4bb`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/IngressMonitorController:SNAPSHOT-PR-317-acd7f240`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/6a517621dcec923ca63ea72d96e0c1ff8a9ac9e0/checks) has Failed!

**Pull request merged**
