### PR TITLE
Allow for multi-user auth config for Pingdom

### PR DESCRIPTION
**Pull request by SinFulNard**
Allow for a config file entry to specify an account email to enable Multi-User authentication: https://www.pingdom.com/api/2.1/#multi-user+authentication

Tested and confirmed working against a multi-user Pingdom account:
```2019/03/20 01:43:27 Monitor Name: bar-smelwani
2019/03/20 01:43:27 Monitor URL: http://smelwani.apps.zzz.yy
2019/03/20 01:43:33 Added monitor for:  bar-smelwani
2019/03/20 01:44:33 Monitor Name: bar-smelwani
2019/03/20 01:44:33 Monitor URL: http://smelwani.apps.zzz.yy
2019/03/20 01:44:34 Delete Monitor:  &{Deletion of check was successful!}```

### CODE REVIEW

**Comment by stakater-user** [comment]
@SinFulNard Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-149-2``

**Comment by kahootali** [comment]
@SinFulNard Looks good, can you please add a test case for this?

**Comment by SinFulNard** [comment]
@kahootali - I've tried to add some test cases, but with my limited Pingdom access, I can't execute and confirm these run. I also updated a little bit of doco to include info on the optional field.

**Comment by stakater-user** [comment]
@SinFulNard Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-149/4/) has Failed!

**Comment by stakater-user** [comment]
@SinFulNard Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-149/5/) has Failed!

**Pull request merged**
