### PR TITLE
Feature/delay

### LINKED ISSUE #184: Allow a delay between Ingress creation and monitor creation
When deploying a new service, DNS updates can take some time to propagate. We typically start getting alerts from uptimerobot right away so we have to either manually pause alerts from uptimerobot, or, apply the Ingress configuration twice (once without the annotation and then again with it).

It would be helpful to have a delay that can be configured either as a duration or timestamp (e.g., wait until X)

### PR DESCRIPTION
**Pull request by lumberj**
Fixes #184

### CODE REVIEW

**Comment by lumberj** [comment]
@rasheedamir so, I still need to add documentation, but I just wanted to get feedback on the naming (e.g., CreationDelay) and using a duration (e.g, "30s").

Also, I wanted to add tests but I get this when running the controller tests,


```
Running tool: /usr/local/bin/go test -timeout 30s github.com/stakater/IngressMonitorController/pkg/controller -run ^(TestAddIngressWithAnnotationEnabledShouldCreateMonitorAndDelete)$

# github.com/stakater/IngressMonitorController/pkg/util
/Users/alancohen/projects/go/src/github.com/stakater/IngressMonitorController/pkg/util/test-helpers.go:43:3: cannot use "github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/stakater/IngressMonitorController/vendor/github.com/openshift/api/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
# github.com/stakater/IngressMonitorController/pkg/kube
/Users/alancohen/projects/go/src/github.com/stakater/IngressMonitorController/pkg/kube/resourcemapper.go:12:2: cannot use &"github.com/stakater/IngressMonitorController/vendor/github.com/openshift/api/route/v1".Route literal (type *"github.com/stakater/IngressMonitorController/vendor/github.com/openshift/api/route/v1".Route) as type "github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/runtime".Object in map value:
	*"github.com/stakater/IngressMonitorController/vendor/github.com/openshift/api/route/v1".Route does not implement "github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "github.com/stakater/IngressMonitorController/vendor/github.com/openshift/api/vendor/k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/runtime".Object
FAIL	github.com/stakater/IngressMonitorController/pkg/controller [build failed]
Error: Tests failed.
```

**Comment by lumberj** [comment]
Also, link for YAML unmarshaling in go playground, https://play.golang.org/p/rMbrfRh8ZRW

**Comment by mrdon-reciprocity** [comment]
:+1:

**Comment by stakater-user** [comment]
@lumberj Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-185/1/) has Failed!

**Comment by stakater-user** [comment]
@lumberj Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-185-2``

**Comment by usamaahmadkhan** [comment]
> @rasheedamir so, I still need to add documentation, but I just wanted to get feedback on the naming (e.g., CreationDelay) and using a duration (e.g, "30s").
> 
> Also, I wanted to add tests but I get this when running the controller tests,
> 
> ```
> Running tool: /usr/local/bin/go test -timeout 30s github.com/stakater/IngressMonitorController/pkg/controller -run ^(TestAddIngressWithAnnotationEnabledShouldCreateMonitorAndDelete)$
> 
> # github.com/stakater/IngressMonitorController/pkg/util
> /Users/alancohen/projects/go/src/github.com/stakater/IngressMonitorController/pkg/util/test-helpers.go:43:3: cannot use "github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/stakater/IngressMonitorController/vendor/github.com/openshift/api/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
> # github.com/stakater/IngressMonitorController/pkg/kube
> /Users/alancohen/projects/go/src/github.com/stakater/IngressMonitorController/pkg/kube/resourcemapper.go:12:2: cannot use &"github.com/stakater/IngressMonitorController/vendor/github.com/openshift/api/route/v1".Route literal (type *"github.com/stakater/IngressMonitorController/vendor/github.com/openshift/api/route/v1".Route) as type "github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/runtime".Object in map value:
> 	*"github.com/stakater/IngressMonitorController/vendor/github.com/openshift/api/route/v1".Route does not implement "github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
> 		have DeepCopyObject() "github.com/stakater/IngressMonitorController/vendor/github.com/openshift/api/vendor/k8s.io/apimachinery/pkg/runtime".Object
> 		want DeepCopyObject() "github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/runtime".Object
> FAIL	github.com/stakater/IngressMonitorController/pkg/controller [build failed]
> Error: Tests failed.
> ```

@lumberj tests are passing as you can see in the latest build. Maybe its due to a change in your local repo.

**Comment by lumberj** [comment]
You're right, looks like a versioning issue. I'll try to fix local env and run tests again.

**Comment by waseem-h** [comment]
@lumberj the name looks good but can we have keep the default behaviour out of the box so that the users upgrading to a newer release won't feel a difference? Like adding a default value in config `creationDelay: 0s`

**Comment by lumberj** [comment]
@waseem-h it is 0s by default, you can check here, https://play.golang.org/p/rMbrfRh8ZRW

When the config yaml looks like, 

```yaml
---
enableMonitorDeletion: "true"
resyncPeriod: 30
```

The Config struct looks like

```
{Providers:[] EnableMonitorDeletion:false MonitorNameTemplate: ResyncPeriod:30 CreationDelay:0s}
```

**Comment by lumberj** [comment]
I still can't get the tests running... but I have a separate question. I don't see anywhere in the controller unit tests where different config settings are being tested.

Here's where the config for the test controller is created, https://github.com/stakater/IngressMonitorController/blob/c57004e8d5a5e57b64fe2c5c84c71ff2f808f920/pkg/controller/controller_test.go#L1067

I suggest being able to pass in override values into `getControllerWithNamespace`

Thoughts on how to approach that?

**Comment by lumberj** [comment]
One way to do it is with functional options:

The `getControllerWithNamespace` function has a variadic argument to pass options

```go
type option interface{}
type configOption func() *config.Config

func getControllerWithNamespace(namespace string, enableDeletion bool, options ...option) *MonitorController {
```

Then, in the function:

```go
	var configOverride *config.Config
	for _, option := range options {
		switch option.(type) {
		case configOption:
			configOverride = option.(configOption)()
		}
	}
```

Then possibly use something like [mergo](https://github.com/imdario/mergo) to merge the override into the config

```go
	c := config.GetControllerConfig()
	if configOverride != nil {
		mergo.Merge(configOverride, &c)
	}
```

**Comment by lumberj** [comment]
@waseem-h  I just updated the PR with the above. I'm still seeing the same errors when trying to run unit tests. What version of Go are you using? Maybe that's the problem.

**Comment by lumberj** [comment]
Is there any way to get test results posted onto PRs?

**Comment by rasheedamir** [comment]
@lumberj yeah I think we need to sort out so, that every can see the output of the failed PR's; I will talk with team

**Comment by lumberj** [comment]
@rasheedamir have you had a chance to check the test results from the latest run? I can't see them, but I added a test case

**Comment by stakater-user** [comment]
@lumberj Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-185/3/) has Failed!

**Comment by kahootali** [comment]
@lumberj The following test is failing

```
=== RUN   TestAddIngressWithCreationDelayShouldCreateMonitorAndDelete
2019/06/10 06:30:44 Reading YAML Configuration /etc/ingress-monitor-controller/config.yaml
2019/06/10 06:30:44 Starting Ingress Monitor controller
2019/06/10 06:30:44 Created ingress "ingress-imc-eevkl".
2019/06/10 06:30:44 Monitor Name: ingress-imc-eevkl-joyoufcgmv
2019/06/10 06:30:44 Monitor URL: http://szqqchhkpdlyafv.com
time="2019-06-10T06:30:45Z" level=info msg="Monitor Added: ingress-imc-eevkl-joyoufcgmv"
time="2019-06-10T06:31:20Z" level=info msg="Monitor Removed: ingress-imc-eevkl-joyoufcgmv"
2019/06/10 06:31:25 Stopping Ingress Monitor controller
--- FAIL: TestAddIngressWithCreationDelayShouldCreateMonitorAndDelete (40.69s)
	controller_test.go:1006: Monitor exists but shouldn't have existed
FAIL
FAIL	github.com/stakater/IngressMonitorController/pkg/controller	255.724s
```

**Comment by stakater-user** [comment]
@lumberj Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-185/4/) has Failed!

**Comment by stakater-user** [comment]
@lumberj Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-185/5/) has Failed!

**Comment by lumberj** [comment]
@kahootali I'm blocked here because I can't run these unit tests locally. https://github.com/stakater/IngressMonitorController/pull/185#issuecomment-497095407

**Comment by usamaahmadkhan** [comment]
@lumberj I think there is some issue with your local repo.
1. Re clone into a new repo.
2. Delete the folder **vendor/** if exists
3. Run `glide update --strip-vendor` in the repo home
3. Make sure the imports on **test-helpers.go** and **resourcemapper.go** and all alias match as per github repo.

go version go1.12.4 linux/amd64

**Comment by lumberj** [comment]
> @lumberj I think there is some issue with your local repo.
> 
> 1. Re clone into a new repo.
> 2. Delete the folder **vendor/** if exists
> 3. Run `glide update --strip-vendor` in the repo home
> 4. Make sure the imports on **test-helpers.go** and **resourcemapper.go** and all alias match as per github repo.
> 
> go version go1.12.4 linux/amd64

This worked, thank you. Running tests and will fix

**Comment by lumberj** [comment]
Getting a very different error now, 

```
go test -timeout 30s github.com/stakater/IngressMonitorController/pkg/controller -run '^(TestAddIngressWithCreationDelayShouldCreateMonitorAndDelete)$'
2019/06/11 13:54:54 Reading YAML Configuration ../../configs/testConfigs/test-config.yaml
--- FAIL: TestAddIngressWithCreationDelayShouldCreateMonitorAndDelete (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x1ac7b35]

goroutine 37 [running]:
testing.tRunner.func1(0xc00044e100)
        /usr/local/Cellar/go/1.12.1/libexec/src/testing/testing.go:830 +0x392
panic(0x1c42ae0, 0x2931500)
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:522 +0x1b5
github.com/stakater/IngressMonitorController/vendor/k8s.io/client-go/kubernetes.(*Clientset).ExtensionsV1beta1(0x0, 0xc000120c00, 0x1)
        /Users/alancohen/projects/go/src/github.com/stakater/IngressMonitorController/vendor/k8s.io/client-go/kubernetes/clientset.go:293 +0x5
github.com/stakater/IngressMonitorController/pkg/controller.getControllerWithNamespace(0xc000042c20, 0xa, 0x6fc23ac01, 0xc000064788, 0x1, 0x1, 0x11)
        /Users/alancohen/projects/go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller_test.go:1147 +0x29f
github.com/stakater/IngressMonitorController/pkg/controller.TestAddIngressWithCreationDelayShouldCreateMonitorAndDelete(0xc00044e100)
        /Users/alancohen/projects/go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller_test.go:909 +0x1d9
testing.tRunner(0xc00044e100, 0x1defea8)
        /usr/local/Cellar/go/1.12.1/libexec/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
        /usr/local/Cellar/go/1.12.1/libexec/src/testing/testing.go:916 +0x35a
FAIL    github.com/stakater/IngressMonitorController/pkg/controller     0.080s
```

**Comment by usamaahmadkhan** [comment]
The error states clearly that its a Segmentation fault.
on line 906. `option` is defined as a function. call it as `option()` on line 909. That will return the `Option` object

**Comment by lumberj** [comment]
The function is called on line 1118, https://github.com/stakater/IngressMonitorController/pull/185/files#diff-a846267007f026d95b52f6baaf249948R1118

I get segfaults on `master` as well.

```
testing.runTests.func1(0xc00044e000)
        /usr/local/Cellar/go/1.12.1/libexec/src/testing/testing.go:1157 +0x78
testing.tRunner(0xc00044e000, 0xc000029e30)
        /usr/local/Cellar/go/1.12.1/libexec/src/testing/testing.go:865 +0xc0
testing.runTests(0xc0003cc000, 0x2937dc0, 0x11, 0x11, 0x0)
        /usr/local/Cellar/go/1.12.1/libexec/src/testing/testing.go:1155 +0x2a9
testing.(*M).Run(0xc00040fb80, 0x0)
        /usr/local/Cellar/go/1.12.1/libexec/src/testing/testing.go:1072 +0x162
main.main()
```

**Comment by usamaahmadkhan** [comment]
@lumberj I ran tests on your branch and the test is passing. both for my personal config and for `test-config.yaml`. Have you set CONFIG_FILE_PATH env. var correctly? Can you check if its not a spelling/spacing problem in the config file plz. Also master is running fine too. I think its a problem inside your config file set as `CONFIG_FILE_PATH`

> go test -v -timeout 30s github.com/stakater/IngressMonitorController/pkg/controller -run '^(TestAddIngressWithCorrectMonitorTemplate)$'
=== RUN   TestAddIngressWithCorrectMonitorTemplate
2019/06/14 12:49:56 Reading YAML Configuration ../../configs/testConfigs/test-config.yaml
2019/06/14 12:49:58 Starting Ingress Monitor controller
2019/06/14 12:50:03 Created ingress "ingress-imc-xmsal".
2019/06/14 12:50:03 Monitor Name: ingress-imc-xmsal-hftqelogun-hello
2019/06/14 12:50:03 Monitor URL: http://zoyiqxururxfdbr.com
2019/06/14 12:50:05 Cannot find monitor with name: ingress-imc-xmsal-hftqelogun-hello
2019/06/14 12:50:05 Not doing anything with this ingress because no annotation exists with name: monitor.stakater.com/enabled
2019/06/14 12:50:10 Stopping Ingress Monitor controller
--- PASS: TestAddIngressWithCorrectMonitorTemplate (14.06s)
PASS
ok  	github.com/stakater/IngressMonitorController/pkg/controller	(cached)

**Comment by usamaahmadkhan** [comment]
@lumberj on line 1117 the case is not getting hit.

**Comment by lumberj** [comment]
> Have you set CONFIG_FILE_PATH env

Sorry, I must have missed that. How should that be set?

**Comment by usamaahmadkhan** [comment]
Refer to the Testing section [here](https://github.com/stakater/IngressMonitorController/blob/afc303ab46c440e6e8f3171a467d8e4efd8f2314/CONTRIBUTING.md#testing). export the file similar to the provided as CONFIG_FILE_PATH. That will get rid of the failing tests.

**Comment by lumberj** [comment]
Ohhhh thank you for pointing that out. I'll followup with the fix today

**Comment by lumberj** [comment]
@usamaahmadkhan are the tests in CI passing now?

**Comment by stakater-user** [comment]
@lumberj Yikes! You better fix it before anyone else finds out! [Build 11](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-185/11/) has Failed!

**Comment by stakater-user** [comment]
@lumberj Yikes! You better fix it before anyone else finds out! [Build 12](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-185/12/) has Failed!

**Comment by usamaahmadkhan** [comment]
@lumberj tests you added are passing. Facing another issue regarding StatusCake on our end. Will merge this as soon as we get the whole pipeline to pass.

**Comment by stakater-user** [comment]
@lumberj Yikes! You better fix it before anyone else finds out! [Build 13](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-185/13/) has Failed!

**Comment by stakater-user** [comment]
@lumberj Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-185-14``

**Comment by stakater-user** [comment]
@lumberj Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-185-15``

**Pull request merged**
