### PR TITLE
Use apiVersion v2(helm v3) for helm chart

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/4e16560f622b424b1ebadb8005e25e74942eda32/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/8978b2afe1c2af6fb216c0545f807eb9d1fbc57d/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/14876e866f6c8d6506d3f8aa3aa44a2f56ecf52c/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/2701bcd7d984c92ab4db08cf111c8ca6fef6817d/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/fdf403708389b1236056309387795df74dc15155/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/8f31abc20a98a2ec1b8001faa510eb82aba6ba8d/checks) has Failed!

**Review by abdulhaseeb2 — APPROVED** [review]
LGTM

**Pull request merged**
