### PR TITLE
Update IMC chart to templatize namespace name

### PR DESCRIPTION
**Pull request by MahnoorAsghar**
Update IMC chart to templatize namespace name

### CODE REVIEW

**Comment by stakater-user** [comment]
@MahnoorAsghar Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/ebd1c7051232eb91bdd7502c5d112df888c11168/checks) has Failed!

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-408-7bb54552`

**Review by hussnain612 — APPROVED** [review]

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-408-88ca720c`

**Comment by MahnoorAsghar** [comment]
> Hi @MahnoorAsghar @hussnain612
> 
> What's the rationale behind letting this chart create and manage a namespace? It's an anti pattern and this kind of behavior should be completely optional.
> 
> If I were to install this chart and set the namespace value to a namespace where I have some other services running and at some point I decided to uninstall this chart it would delete the namespace as it is now "owned" by this release.
> 
> The chart should instead use `namespace: {{ .Release.Namespace }}` which allows the user to tell helm the target namespace for this chart installation.
> 
> This should be inside a if clause: https://github.com/stakater/IngressMonitorController/blob/master/charts/ingressmonitorcontroller/templates/namespace.yaml#L1
> 
> This value should not be set by default: https://github.com/stakater/IngressMonitorController/blob/master/charts/ingressmonitorcontroller/values.yaml#L90

Hi @hgranillo,
I didn't forsee the issue you highlighted, so thank you for pointing it out! 
Please go ahead and make a PR with the changes you mentioned. Our use case would be handled just as well if we made the .Values.namespace field optional, and would make for a better approach :).

Please feel free to tag me for a review on your PR. Thanks!

**Pull request merged**
