### PR TITLE
fix path of templates folder in readme

### PR DESCRIPTION
**Pull request by rasheedamir**
the path wasn't complete

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.tools.stackator.com/job/Stakater/job/IngressMonitorController/job/PR-84/1/) has Failed!

**Comment by rasheedamir** [comment]
@waseem-h @hazim1093 again just an update in readme broke tests! we must fix the root cause of this issue

**Comment by hazim1093** [comment]
The build failed because of the same reason mentioned in https://github.com/stakater/IngressMonitorController/issues/74

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:PR-84-3``

**Pull request merged**
