### PR TITLE
StatusCake: Use regions instead of node_locations

### PR DESCRIPTION
**Pull request by tibuntu**
Hi, as described in #540 setting nodeLocations didn't have any affect.

Thanks to the response of @MuneebAijaz I was able to track down the required changes.

I was able to build the IngressMonitorController locally, and after deploying my tag to Kubernetes, the regions were set correctly again.

### CODE REVIEW

**Review by MuneebAijaz — APPROVED** [review]

**Comment by tibuntu** [comment]
Hi @MuneebAijaz, done.

**Comment by tibuntu** [comment]
@MuneebAijaz any chance this is going to me merged soon?

**Comment by MuneebAijaz** [comment]
@tibuntu apologies, busy days at work

**Comment by tibuntu** [comment]
@MuneebAijaz that was quicker than expected. Sorry for any pressure, I really love this piece of software but the broken functionally stopped us from using it! Thank you very much!

**Comment by MuneebAijaz** [comment]
@tibuntu no worries, i understand the frustration if any. feel free to tag anytime if its urgent. Difficult to keep track of many things during the day

**Pull request merged**
