### PR TITLE
Update instructions to run local tests

### PR DESCRIPTION
**Pull request by hazim1093**
Update instructions to run tests on local machines after code restructuring

### CODE REVIEW

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.tools.stackator.com/job/Stakater/job/IngressMonitorController/job/PR-72/2/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:PR-72-3``

**Comment by gempesaw** [comment]
yes seems to work fine except one of the config tests fails, I guess because the `CONFIG_FILE_PATH`  env var overrides the config the test wants it to load ?

```
make test
"go" test -v ./...
?   	_/Users/dgempesaw/opt/IngressMonitorController	[no test files]
=== RUN   TestConfigWithCorrectValues
2018/06/21 09:07:27 Reading YAML Configuration
--- FAIL: TestConfigWithCorrectValues (0.00s)
	config_test.go:15: Marshalled config and correct config do not match
=== RUN   TestConfigWithIncorrectProviderValues
2018/06/21 09:07:27 Reading YAML Configuration
--- PASS: TestConfigWithIncorrectProviderValues (0.00s)
=== RUN   TestConfigWithIncorrectEnableFlag
2018/06/21 09:07:27 Reading YAML Configuration
--- PASS: TestConfigWithIncorrectEnableFlag (0.00s)
=== RUN   TestConfigWithoutProvider
2018/06/21 09:07:27 Reading YAML Configuration
--- PASS: TestConfigWithoutProvider (0.00s)
=== RUN   TestConfigWithoutEnabledFlag
2018/06/21 09:07:27 Reading YAML Configuration
--- PASS: TestConfigWithoutEnabledFlag (0.00s)
=== RUN   TestConfigWithEmptyConfig
2018/06/21 09:07:27 Reading YAML Configuration
--- PASS: TestConfigWithEmptyConfig (0.00s)
FAIL
FAIL	_/Users/dgempesaw/opt/IngressMonitorController/pkg/config	0.011s
=== RUN   TestAddIngressWithNoAnnotationShouldNotCreateMonitor
2018/06/21 09:07:29 Reading YAML Configuration
2018/06/21 09:07:29 Starting Ingress Monitor controller
2018/06/21 09:07:34 Created ingress "testingingress".
2018/06/21 09:07:34 Monitor Name: testingingress-test
2018/06/21 09:07:34 Monitor URL: http://google.com
2018/06/21 09:07:35 Cannot find monitor with name: testingingress-test
2018/06/21 09:07:35 Not doing anything with this ingress because no annotation exists with name: monitor.stakater.com/enabled
2018/06/21 09:07:39 Reading YAML Configuration
2018/06/21 09:07:39 Stopping Ingress Monitor controller
--- PASS: TestAddIngressWithNoAnnotationShouldNotCreateMonitor (10.09s)
=== RUN   TestAddIngressWithCorrectMonitorTemplate
2018/06/21 09:07:39 Reading YAML Configuration
2018/06/21 09:07:39 Starting Ingress Monitor controller
2018/06/21 09:07:39 Cannot find monitor with name: testingingress-test
2018/06/21 09:07:44 Monitor Name: testingingress-test-hello
2018/06/21 09:07:44 Monitor URL: http://google.com
2018/06/21 09:07:44 Created ingress "testingingress".
2018/06/21 09:07:44 Cannot find monitor with name: testingingress-test-hello
2018/06/21 09:07:44 Not doing anything with this ingress because no annotation exists with name: monitor.stakater.com/enabled
2018/06/21 09:07:49 Reading YAML Configuration
--- PASS: TestAddIngressWithCorrectMonitorTemplate (10.08s)
2018/06/21 09:07:49 Stopping Ingress Monitor controller
=== RUN   TestInvalidMonitorTemplateShouldPanic
--- PASS: TestInvalidMonitorTemplateShouldPanic (0.00s)
=== RUN   TestAddIngressWithAnnotationEnabledShouldCreateMonitorAndDelete
2018/06/21 09:07:49 Reading YAML Configuration
2018/06/21 09:07:49 Starting Ingress Monitor controller
2018/06/21 09:07:49 Created ingress "testingingress".
2018/06/21 09:07:49 Cannot find monitor with name: testingingress-test-hello
2018/06/21 09:07:49 Monitor Name: testingingress-test
2018/06/21 09:07:49 Monitor URL: http://google.com
2018/06/21 09:07:50 Monitor Added: testingingress-test
2018/06/21 09:07:54 Reading YAML Configuration
2018/06/21 09:07:55 Monitor Removed: testingingress-test
2018/06/21 09:07:59 Reading YAML Configuration
--- PASS: TestAddIngressWithAnnotationEnabledShouldCreateMonitorAndDelete (10.20s)
=== RUN   TestAddIngressWithAnnotationDisabledShouldNotCreateMonitor
2018/06/21 09:08:00 Stopping Ingress Monitor controller
2018/06/21 09:08:00 Reading YAML Configuration
2018/06/21 09:08:00 Starting Ingress Monitor controller
2018/06/21 09:08:00 Created ingress "testingingress".
2018/06/21 09:08:00 Monitor Name: testingingress-test
2018/06/21 09:08:00 Monitor URL: http://google.com
2018/06/21 09:08:00 Cannot find monitor with name: testingingress-test
2018/06/21 09:08:05 Reading YAML Configuration
--- PASS: TestAddIngressWithAnnotationDisabledShouldNotCreateMonitor (5.27s)
2018/06/21 09:08:05 Stopping Ingress Monitor controller
=== RUN   TestUpdateIngressWithAnnotationDisabledShouldNotCreateMonitor
2018/06/21 09:08:05 Reading YAML Configuration
2018/06/21 09:08:05 Created ingress "testingingress".
2018/06/21 09:08:05 Cannot find monitor with name: testingingress-test
2018/06/21 09:08:10 Starting Ingress Monitor controller
2018/06/21 09:08:10 Updated ingress "testingingress".
2018/06/21 09:08:10 Reading YAML Configuration
--- PASS: TestUpdateIngressWithAnnotationDisabledShouldNotCreateMonitor (5.10s)
=== RUN   TestUpdateIngressWithAnnotationEnabledShouldCreateMonitorAndDelete
2018/06/21 09:08:10 Stopping Ingress Monitor controller
2018/06/21 09:08:10 Reading YAML Configuration
2018/06/21 09:08:10 Created ingress "testingingress".
2018/06/21 09:08:15 Starting Ingress Monitor controller
2018/06/21 09:08:15 Updated ingress "testingingress".
2018/06/21 09:08:15 Monitor Name: testingingress-test
2018/06/21 09:08:15 Monitor URL: http://google.com
2018/06/21 09:08:15 Monitor Added: testingingress-test
2018/06/21 09:08:18 Reading YAML Configuration
2018/06/21 09:08:18 Monitor Removed: testingingress-test
2018/06/21 09:08:21 Reading YAML Configuration
--- PASS: TestUpdateIngressWithAnnotationEnabledShouldCreateMonitorAndDelete (11.14s)
=== RUN   TestUpdateIngressWithAnnotationFromEnabledToDisabledShouldDeleteMonitor
2018/06/21 09:08:21 Stopping Ingress Monitor controller
2018/06/21 09:08:21 Reading YAML Configuration
2018/06/21 09:08:21 Created ingress "testingingress".
2018/06/21 09:08:26 Starting Ingress Monitor controller
2018/06/21 09:08:26 Monitor Name: testingingress-test
2018/06/21 09:08:26 Monitor URL: http://google.com
2018/06/21 09:08:26 Monitor Added: testingingress-test
2018/06/21 09:08:31 Reading YAML Configuration
2018/06/21 09:08:31 Monitor Name: testingingress-test
2018/06/21 09:08:31 Monitor URL: http://google.com
2018/06/21 09:08:31 Updated ingress "testingingress".
2018/06/21 09:08:31 Monitor Removed: testingingress-test
2018/06/21 09:08:34 Reading YAML Configuration
--- PASS: TestUpdateIngressWithAnnotationFromEnabledToDisabledShouldDeleteMonitor (13.16s)
2018/06/21 09:08:34 Stopping Ingress Monitor controller
=== RUN   TestUpdateIngressWithNewURLShouldUpdateMonitor
2018/06/21 09:08:34 Reading YAML Configuration
2018/06/21 09:08:34 Created ingress "testingingress".
2018/06/21 09:08:34 Cannot find monitor with name: testingingress-test
2018/06/21 09:08:39 Starting Ingress Monitor controller
2018/06/21 09:08:39 Monitor Name: testingingress-test
2018/06/21 09:08:39 Monitor URL: http://google.com
2018/06/21 09:08:39 Monitor Added: testingingress-test
2018/06/21 09:08:44 Reading YAML Configuration
2018/06/21 09:08:44 Updated ingress "testingingress".
2018/06/21 09:08:44 Monitor Name: testingingress-test
2018/06/21 09:08:44 Monitor URL: http://facebook.com
2018/06/21 09:08:44 Monitor already exists for ingress: testingingress-test
2018/06/21 09:08:44 Monitor Updated: testingingress-test
2018/06/21 09:08:47 Reading YAML Configuration
2018/06/21 09:08:47 Reading YAML Configuration
2018/06/21 09:08:48 Monitor Removed: testingingress-test
2018/06/21 09:08:50 Reading YAML Configuration
--- PASS: TestUpdateIngressWithNewURLShouldUpdateMonitor (16.35s)
=== RUN   TestUpdateIngressWithEnabledAnnotationShouldCreateMonitorAndDelete
2018/06/21 09:08:51 Stopping Ingress Monitor controller
2018/06/21 09:08:51 Reading YAML Configuration
2018/06/21 09:08:51 Created ingress "testingingress".
2018/06/21 09:08:56 Starting Ingress Monitor controller
2018/06/21 09:08:56 Updated ingress "testingingress".
2018/06/21 09:08:56 Monitor Name: testingingress-test
2018/06/21 09:08:56 Monitor URL: http://google.com
2018/06/21 09:08:56 Monitor Added: testingingress-test
2018/06/21 09:08:59 Reading YAML Configuration
2018/06/21 09:08:59 Monitor Removed: testingingress-test
2018/06/21 09:09:02 Reading YAML Configuration
--- PASS: TestUpdateIngressWithEnabledAnnotationShouldCreateMonitorAndDelete (11.16s)
=== RUN   TestAddIngressWithAnnotationEnabledButDisableDeletionShouldCreateMonitorAndNotDelete
2018/06/21 09:09:02 Stopping Ingress Monitor controller
2018/06/21 09:09:02 Reading YAML Configuration
2018/06/21 09:09:02 Starting Ingress Monitor controller
2018/06/21 09:09:02 Created ingress "testingingress".
2018/06/21 09:09:02 Monitor Name: testingingress-test
2018/06/21 09:09:02 Monitor URL: http://google.com
2018/06/21 09:09:02 Monitor Added: testingingress-test
2018/06/21 09:09:07 Reading YAML Configuration
2018/06/21 09:09:12 Reading YAML Configuration
2018/06/21 09:09:12 Reading YAML Configuration
2018/06/21 09:09:12 Monitor Removed: testingingress-test
--- PASS: TestAddIngressWithAnnotationEnabledButDisableDeletionShouldCreateMonitorAndNotDelete (10.64s)
=== RUN   TestAddIngressWithAnnotationAssociatedWithServiceAndHasPodShouldCreateMonitor
2018/06/21 09:09:12 Stopping Ingress Monitor controller
2018/06/21 09:09:12 Reading YAML Configuration
2018/06/21 09:09:12 Starting Ingress Monitor controller
2018/06/21 09:09:12 Created ingress "testingingress".
2018/06/21 09:09:12 Monitor Name: testingingress-test
2018/06/21 09:09:12 Monitor URL: http://google.com/health
2018/06/21 09:09:13 Monitor Added: testingingress-test
2018/06/21 09:09:17 Reading YAML Configuration
2018/06/21 09:09:17 Reading YAML Configuration
2018/06/21 09:09:33 Reading YAML Configuration
2018/06/21 09:09:33 Reading YAML Configuration
2018/06/21 09:09:33 Monitor Removed: testingingress-test
--- PASS: TestAddIngressWithAnnotationAssociatedWithServiceAndHasPodShouldCreateMonitor (20.64s)
=== RUN   TestAddIngressWithAnnotationAssociatedWithServiceAndHasPodButNoProbesShouldCreateMonitor
2018/06/21 09:09:33 Stopping Ingress Monitor controller
2018/06/21 09:09:33 Reading YAML Configuration
2018/06/21 09:09:33 Starting Ingress Monitor controller
2018/06/21 09:09:33 Created ingress "testingingress".
2018/06/21 09:09:33 Monitor Name: testingingress-test
2018/06/21 09:09:33 Monitor URL: http://google.com
2018/06/21 09:09:33 Monitor Added: testingingress-test
2018/06/21 09:09:38 Reading YAML Configuration
2018/06/21 09:09:38 Reading YAML Configuration
2018/06/21 09:09:53 Reading YAML Configuration
2018/06/21 09:09:53 Reading YAML Configuration
2018/06/21 09:09:54 Monitor Removed: testingingress-test
--- PASS: TestAddIngressWithAnnotationAssociatedWithServiceAndHasPodButNoProbesShouldCreateMonitor (20.57s)
2018/06/21 09:09:54 Stopping Ingress Monitor controller
=== RUN   TestAddIngressWithHealthAnnotationAssociatedWithServiceAndHasPodShouldCreateMonitor
2018/06/21 09:09:54 Reading YAML Configuration
2018/06/21 09:09:54 Starting Ingress Monitor controller
2018/06/21 09:09:54 Created ingress "testingingress".
2018/06/21 09:09:54 Monitor Name: testingingress-test
2018/06/21 09:09:54 Monitor URL: http://google.com/hello
2018/06/21 09:09:54 Monitor Added: testingingress-test
2018/06/21 09:09:59 Reading YAML Configuration
2018/06/21 09:09:59 Reading YAML Configuration
2018/06/21 09:10:14 Reading YAML Configuration
2018/06/21 09:10:14 Reading YAML Configuration
2018/06/21 09:10:14 Monitor Removed: testingingress-test
--- PASS: TestAddIngressWithHealthAnnotationAssociatedWithServiceAndHasPodShouldCreateMonitor (20.40s)
=== RUN   TestAddIngressWithAnnotationAssociatedWithServiceAndHasNoPodShouldCreateMonitor
2018/06/21 09:10:14 Stopping Ingress Monitor controller
2018/06/21 09:10:14 Reading YAML Configuration
2018/06/21 09:10:14 Starting Ingress Monitor controller
2018/06/21 09:10:14 Created ingress "testingingress".
2018/06/21 09:10:14 Monitor Name: testingingress-test
2018/06/21 09:10:14 Monitor URL: http://google.com
2018/06/21 09:10:14 Monitor Added: testingingress-test
2018/06/21 09:10:19 Reading YAML Configuration
2018/06/21 09:10:19 Reading YAML Configuration
2018/06/21 09:10:34 Reading YAML Configuration
2018/06/21 09:10:34 Reading YAML Configuration
2018/06/21 09:10:34 Monitor Removed: testingingress-test
--- PASS: TestAddIngressWithAnnotationAssociatedWithServiceAndHasNoPodShouldCreateMonitor (20.47s)
2018/06/21 09:10:34 Stopping Ingress Monitor controller
PASS
ok  	_/Users/dgempesaw/opt/IngressMonitorController/pkg/controller	185.277s
=== RUN   TestCreateHttpClient
--- PASS: TestCreateHttpClient (0.00s)
=== RUN   TestPostShouldReturn405Status
--- PASS: TestPostShouldReturn405Status (0.20s)
=== RUN   TestAddHeaders
--- PASS: TestAddHeaders (0.00s)
PASS
ok  	_/Users/dgempesaw/opt/IngressMonitorController/pkg/http	(cached)
?   	_/Users/dgempesaw/opt/IngressMonitorController/pkg/kube	[no test files]
=== RUN   TestIngressWrapper_getURL
=== RUN   TestIngressWrapper_getURL/TestGetUrlWithEmptyPath
=== RUN   TestIngressWrapper_getURL/TestGetUrlWithHelloPath
=== RUN   TestIngressWrapper_getURL/TestGetUrlWithNoPath
=== RUN   TestIngressWrapper_getURL/TestGetUrlWithForceHTTPSAnnotation
=== RUN   TestIngressWrapper_getURL/TestGetUrlWithForceHTTPSAnnotationOff
=== RUN   TestIngressWrapper_getURL/TestGetUrlWithOverridePathAnnotation
--- PASS: TestIngressWrapper_getURL (0.09s)
    --- PASS: TestIngressWrapper_getURL/TestGetUrlWithEmptyPath (0.00s)
    --- PASS: TestIngressWrapper_getURL/TestGetUrlWithHelloPath (0.00s)
    --- PASS: TestIngressWrapper_getURL/TestGetUrlWithNoPath (0.00s)
    --- PASS: TestIngressWrapper_getURL/TestGetUrlWithForceHTTPSAnnotation (0.00s)
    --- PASS: TestIngressWrapper_getURL/TestGetUrlWithForceHTTPSAnnotationOff (0.00s)
    --- PASS: TestIngressWrapper_getURL/TestGetUrlWithOverridePathAnnotation (0.00s)
PASS
ok  	_/Users/dgempesaw/opt/IngressMonitorController/pkg/kube/wrappers	0.111s
?   	_/Users/dgempesaw/opt/IngressMonitorController/pkg/models	[no test files]
=== RUN   TestMonitorServiceProxyOfTypeWithCorrectType
--- PASS: TestMonitorServiceProxyOfTypeWithCorrectType (0.00s)
=== RUN   TestMonitorServiceProxyOfTypeWithWrongType
2018/06/20 13:40:17 No such provider found: Testing
--- PASS: TestMonitorServiceProxyOfTypeWithWrongType (0.00s)
PASS
ok  	_/Users/dgempesaw/opt/IngressMonitorController/pkg/monitors	(cached)
testing: warning: no tests to run
PASS
ok  	_/Users/dgempesaw/opt/IngressMonitorController/pkg/monitors/pingdom	(cached) [no tests to run]
=== RUN   TestUptimeMonitorMonitorToBaseMonitorMapper
--- PASS: TestUptimeMonitorMonitorToBaseMonitorMapper (0.00s)
=== RUN   TestUptimeMonitorMonitorsToBaseMonitorsMapper
--- PASS: TestUptimeMonitorMonitorsToBaseMonitorsMapper (0.00s)
=== RUN   TestAddMonitorWithCorrectValues
2018/06/21 09:07:28 Reading YAML Configuration
2018/06/21 09:07:28 Monitor Added: google-test
2018/06/21 09:07:28 Monitor Removed: google-test
--- PASS: TestAddMonitorWithCorrectValues (0.42s)
=== RUN   TestUpdateMonitorWithCorrectValues
2018/06/21 09:07:28 Reading YAML Configuration
2018/06/21 09:07:28 Monitor Added: google-test
2018/06/21 09:07:28 Monitor Updated: google-test
2018/06/21 09:07:28 Monitor Removed: google-test
--- PASS: TestUpdateMonitorWithCorrectValues (0.29s)
=== RUN   TestAddMonitorWithIncorrectValues
2018/06/21 09:07:28 Reading YAML Configuration
2018/06/21 09:07:28 Monitor couldn't be added: google-test
2018/06/21 09:07:28 api_key=dummy-api-key&format=json&type=1&url=https%3A%2F%2Fgoogle.com&friendly_name=google-test&alert_contacts=0596743_0_0
--- PASS: TestAddMonitorWithIncorrectValues (0.19s)
PASS
ok  	_/Users/dgempesaw/opt/IngressMonitorController/pkg/monitors/uptimerobot	0.915s
?   	_/Users/dgempesaw/opt/IngressMonitorController/pkg/util	[no test files]
make: *** [test] Error 1
bash-3.2$ 
```

**Comment by hazim1093** [comment]
@gempesaw I've moved values in the config_test to constants, and mentioned that in the readme, so it's easier to change. I know not Ideal, but it would work for someone who wants to run these tests locally. 

@waseem-h What do you think ?

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:PR-72-4``

**Comment by gempesaw** [comment]
awesome, I checked out your branch and ran the tests locally and everything passes out of the box :D

**Pull request merged**
