### PR TITLE
Remove regex capture group from path

### PR DESCRIPTION
**Pull request by hazim1093**
Removes regex capture groups from path when creating a monitor. 
Required if ingresses have a regex capture group to support rewrite-target for nginx-ingress

https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
LGTM

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins-delivery.stakater.com/job/Stakater/job/IngressMonitorController/job/PR-282/1/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-282-2``

**Comment by rasheedamir** [comment]
@hazim1093 plz get this merged

**Review by ahmedwaleedmalik — APPROVED** [review]

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-282-4``

**Pull request merged**
