### PR TITLE
Allow to enable resync in the controller to get updates from Ingress endpoints

### LINKED ISSUE #147: IngressMonitorController should update URL on pod changes
Currently, it seems that IngressMonitorController discovers the URLs to be monitored only at startup or on Ingress changes.

If the readiness URLs of the pods behind a ingress changes, the URLs are not updated automatically.

The issue could be solved by doing regularly a full-scan of all monitors and update the URLs if necessary.
My suggestion would be to try simply a resyncPeriod > 0 in 
https://github.com/stakater/IngressMonitorController/blob/2c627d18163c00b2826c694b78c770ba3eae509f/pkg/controller/controller.go#L53

### PR DESCRIPTION
**Pull request by xanonid**
Closes #147

### CODE REVIEW

**Comment by stakater-user** [comment]
@xanonid Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-155-2``

**Comment by stakater-user** [comment]
@xanonid Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-155/3/) has Failed!

**Comment by stakater-user** [comment]
@xanonid Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-155-5``

**Comment by kahootali** [comment]
@xanonid Can you please make the **resynchPeriod** a config parameter, and set the default value to 0, as some users might not need this functionality and if one needs, he can set it?

**Comment by rasheedamir** [comment]
@xanonid can you please take care of last comment so, that we can merge this PR?

**Comment by xanonid** [comment]
@rasheedamir I will update the PR.

**Comment by xanonid** [comment]
@rasheedamir I updated the PR. The resync feature should now be off by default (i.e. period set to zero). The config does not need to be adapted to be fully backward-compatible.

**Comment by stakater-user** [comment]
@xanonid Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-155-8``

**Comment by stakater-user** [comment]
@xanonid Yikes! You better fix it before anyone else finds out! [Build 9](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-155/9/) has Failed!

**Comment by stakater-user** [comment]
@xanonid Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-155-10``

**Comment by kahootali** [comment]
@xanonid Can you please add this parameter in values.yaml.tmpl file as well with default value to be 0?

**Comment by xanonid** [comment]
@kahootali I updated values.yaml.tmpl and corresponding files - the PR is also now rebased to latest master.

**Comment by stakater-user** [comment]
@xanonid Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-155-12``

**Pull request merged**
