### PR TITLE
Fix Pipeline Failure due to old test packages and kind version

### PR DESCRIPTION
**Pull request by abdulhaseeb2**

### CODE REVIEW

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/c234efe3dbf2104e62a4b00c18ef3d235a5760d9/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/c27442791caa24520ee8c51ba0d5350f1ca8e2c6/checks) has Failed!

**Comment by stakater-user** [comment]
@hussnain612 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/da40166b13cafd7bfa15fdef446768da09af2a13/checks) has Failed!

**Comment by stakater-user** [comment]
@hussnain612 Image is available for testing. `docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-386-22141556`

**Comment by stakater-user** [comment]
@hussnain612 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/b7b2efc47927fab4a40651fd55f12768ce0088bd/checks) has Failed!

**Review by usamaahmadkhan — APPROVED** [review]

**Pull request merged**
