### PR TITLE
Update IMC v1 to be compatible with Pingdom API v3

### PR DESCRIPTION
**Pull request by namm2**
I'm still using IMC v1 (not upgrade to operator yet), so having Pingdom API v3 is nice.

### CODE REVIEW

**Comment by stakater-user** [comment]
@namm2 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins-delivery.stakater.com/job/Stakater/job/IngressMonitorController/job/PR-286/1/) has Failed!

**Comment by stakater-user** [comment]
@namm2 Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-286-2``

**Review by ahmedwaleedmalik — APPROVED** [review]
LGTM

**Comment by namm2** [comment]
@ahmedwaleedmalik Can you create a tag for this commit please? So we'll have a new docker image instead of `SNAPSHOT-PR-286-2`

**Comment by ahmedwaleedmalik** [comment]
Sure thing @namm2, i am updating the pipeline so that thing is automated along with updating the chart(for the previous release). Will let you know here when the new release is ready

**Comment by ahmedwaleedmalik** [comment]
@namm2  available at https://github.com/stakater/IngressMonitorController/releases/tag/v1.0.103

**Pull request merged**
