### PR TITLE
Alert contacts configurable

### PR DESCRIPTION
**Pull request by tuananhnguyen-ct**
This provides support for configuring alert contacts via annotation, ref https://github.com/stakater/IngressMonitorController/issues/222

### CODE REVIEW

**Comment by stakater-user** [comment]
@tuananhnguyen-ct Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-228-1``

**Comment by usamaahmadkhan** [comment]
@tuananhnguyen-ct plz add docs for the new annotation here: https://github.com/stakater/IngressMonitorController/blob/master/docs/pingdom-configuration.md

**Comment by stakater-user** [comment]
@tuananhnguyen-ct Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-228-2``

**Comment by stakater-user** [comment]
@tuananhnguyen-ct Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-228-3``

**Comment by usamaahmadkhan** [comment]
@tuananhnguyen-ct right now we don't have a pingdom account so we cannot actually test the changes. The commit looks good. If you have tested this locally an it works as expected, i'll merge this.

**Comment by tuananhnguyen-ct** [comment]
I'll test the new image again and confirm here shortly.

**Comment by tuananhnguyen-ct** [comment]
Tested & working, thanks.

**Pull request merged**
