### PR TITLE
bug: add check for empty tls hosts

### PR DESCRIPTION
**Pull request by tuananhnguyen-ct**
Quick fix for issue https://github.com/stakater/IngressMonitorController/issues/200

### CODE REVIEW

**Comment by stakater-user** [comment]
@tuananhnguyen-ct Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-201/1/) has Failed!

**Comment by stakater-user** [comment]
@tuananhnguyen-ct Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-201/2/) has Failed!

**Comment by usamaahmadkhan** [comment]
@tuananhnguyen-ct Jenkins spewing the following error:

>  make test
> "go" test -v ./...
>  github.com/********/IngressMonitorController/pkg/kube/wrappers
> pkg/kube/wrappers/ingress-wrapper.go:23:90: cannot convert nil to type "github.com/********/IngressMonitorController/vendor/k8s.io/api/extensions/v1beta1".IngressTLS
>  github.com/********/IngressMonitorController/pkg/kube/wrappers
> pkg/kube/wrappers/ingress-wrapper.go:23:90: cannot convert nil to type "github.com/********/IngressMonitorController/vendor/k8s.io/api/extensions/v1beta1".IngressTLS
> make: *** [Makefile:40: test] Error 2

**Comment by stakater-user** [comment]
@tuananhnguyen-ct Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-201/3/) has Failed!

**Comment by stakater-user** [comment]
@tuananhnguyen-ct Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-201-4``

**Comment by usamaahmadkhan** [comment]
@tuananhnguyen-ct it would be nice to have test case for this so we know any future changes are not breaking this feature.

**Comment by rasheedamir** [comment]
@tuananhnguyen-ct can you plz add a test case so, that we can merge this PR? great thanks!

**Comment by tuananhnguyen-ct** [comment]
Yes I will do soon, sorry was busy last week :|

**Comment by stakater-user** [comment]
@tuananhnguyen-ct Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-201-5``

**Pull request merged**
