### PR TITLE
Fixed log.info() syntax

### PR DESCRIPTION
**Pull request by adamstrawson**
@ahmedwaleedmalik Hit a similar error again, found a few more cases of that syntax error on StatusCake

### CODE REVIEW

**Comment by stakater-user** [comment]
@adamstrawson Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/a17c9e9039fd72a9aca19abf82e0615a668787fd/checks) has Failed!

**Comment by ahmedwaleedmalik** [comment]
Can you check the pipeline? Your changes are generating linting errors.

```
pkg/monitors/statuscake/statuscake-monitor.go:277:13: cannot convert "Monitor Added: " (untyped string constant) to int (typecheck)
			log.Info("Monitor Added: " + fa.InsertID)
```

**Comment by adamstrawson** [comment]
Odd that it's complaining, I pretty much copied the same fix you did in #342 

I'll take a look in the morning 👍

**Comment by ahmedwaleedmalik** [comment]
Sure thing :)

It's trying to append an integer to a string in your case; that's why it's failing.

**Comment by stakater-user** [comment]
@adamstrawson Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/1efd0cd020b05b1a1829b10ec0d5cc31c4a29829/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/IngressMonitorController:SNAPSHOT-PR-343-1efd0cd0`

**Review by ahmedwaleedmalik — APPROVED** [review]

**Pull request merged**
