### PR TITLE
add generic documentation for seo

### PR DESCRIPTION
**Pull request by rasheedamir**
add common search queries which can help people discover IMC

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.tools.stackator.com/job/Stakater/job/IngressMonitorController/job/PR-100/1/) has Failed!

**Comment by rasheedamir** [comment]
@waseem-h this is annonying that build fails on just updates of README's :(

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.tools.stackator.com/job/Stakater/job/IngressMonitorController/job/PR-100/2/) has Failed!

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:PR-100-4``

**Pull request merged**
