### PR TITLE
Provide a way to override the monitor name with a field monitorName 

### PR DESCRIPTION
**Pull request by dandonovsc**
Added an explicit field on the EndpointMonitor resource to allow an optional monitor name override that can use special or upper case characters.
The current implementation uses `metadata.name` + `metadata.namespace` ( or {{.Name}} - {{.Namespace}}) in an optional template. The limitation here is the validation is Kubernetes restricting the character set to regex pattern:

`a lowercase RFC 1123 subdomain must consist of lower case alphanumeric
characters, '-' or '.', and must start and end with an alphanumeric
character (e.g. 'example.com', regex used for validation is
'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

### CODE REVIEW

**Comment by stakater-user** [comment]
@dandonovsc Image is available for testing. `docker pull stakater/IngressMonitorController:SNAPSHOT-PR-376-9a6200d3`

**Comment by dandonovsc** [comment]
> 
$ docker pull stakater/IngressMonitorController:SNAPSHOT-PR-376-9a6200d3
invalid reference format: repository name must be lowercase

**Comment by stakater-user** [comment]
@dandonovsc Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/f93d317aaa0e50bb8e48cb918ebbbc289815fc06/checks) has Failed!

**Comment by stakater-user** [comment]
@dandonovsc Image is available for testing. `docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-376-90c3caaf`

**Pull request closed without merging**
