### PR TITLE
Fixes log format across the board

### PR DESCRIPTION
**Pull request by adamstrawson**
After the change to use the log package `sigs.k8s.io/controller-runtime/pkg/log` (Ref: https://github.com/stakater/IngressMonitorController/commit/c9c426f51ffd1737370137cb50034063fa53bf51), logging across various areas results in errors like `odd number of arguments passed as key-value pairs for logging`.

A couple have already been fixed in previous PR's (#342 & #343), but we keep hitting the error in other places. 

I've done a full sweep of the codebase and fixed any mentions of the previous format. 

I was unable to run the tests locally as I don't have the appropriate configs, but I'm able to build successfully.

### CODE REVIEW

**Comment by stakater-user** [comment]
@adamstrawson Image is available for testing. `docker pull stakater/IngressMonitorController:SNAPSHOT-PR-344-8f966f25`

**Comment by adamstrawson** [comment]
CC: @ahmedwaleedmalik

**Comment by ahmedwaleedmalik** [comment]
Thank you for taking care of this @adamstrawson :)

**Review by ahmedwaleedmalik — APPROVED** [review]
LGTM

**Pull request merged**
