### PR TITLE
Update the major version

### PR DESCRIPTION
**Pull request by hussnain612**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hussnain612 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/174d429eac9b7d2047ee8a3dbe44ae3bb36aa7c3/checks) has Failed!

**Comment by stakater-user** [comment]
@hussnain612 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/6ac4f7f5fba4fa1f6adbee122882c00f3a8618fd/checks) has Failed!

**Comment by stakater-user** [comment]
@hussnain612 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/5e5c28c8b736d7d5430e6d08935260f180dd845c/checks) has Failed!

**Comment by stakater-user** [comment]
@hussnain612 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/e6ad361833b0b6009d08bac2eb54f638a4e1a122/checks) has Failed!

**Comment by stakater-user** [comment]
@hussnain612 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/f0230a8d9dabef1ec3199dd2d7a94bd56fdd0075/checks) has Failed!

**Comment by stakater-user** [comment]
@hussnain612 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/0a6f2444deff2f9d277fc77aebf77a9d6c836002/checks) has Failed!

**Comment by stakater-user** [comment]
@hussnain612 Image is available for testing. `docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-392-0a6f2444`

**Comment by stakater-user** [comment]
@hussnain612 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/81334d1e0b16cccc0c6afe649280f8a329b3ec67/checks) has Failed!

**Comment by stakater-user** [comment]
@hussnain612 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/eb3b6a3f6f85e11a3b52fe589269f59f91ca3f66/checks) has Failed!

**Comment by stakater-user** [comment]
@hussnain612 Image is available for testing. `docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-392-f304c4ba`

**Review by tanalam2411 — APPROVED** [review]

**Pull request merged**
