### PR TITLE
Add basic auth support for statuscake (#148) 🍰

### PR DESCRIPTION
**Pull request by DhiaTN**
#### What this PR does / why we need it:
Add support for basic auth (statuscake.com) based on the official API [documentation](https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md).

#### Special notes for your reviewer:
N/A

### CODE REVIEW

**Comment by stakater-user** [comment]
@DhiaTN Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-170/1/) has Failed!

**Comment by stakater-user** [comment]
@DhiaTN Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-170/2/) has Failed!

**Comment by stakater-user** [comment]
@DhiaTN Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-170/4/) has Failed!

**Comment by usamaahmadkhan** [comment]
@DhiaTN Following testcase is failing because of your changes. Kindly look into it. 

> TestUpdateIngressWithAnnotationEnabledShouldCreateMonitorAndDelete

**Comment by stakater-user** [comment]
@DhiaTN Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-170-6``

**Comment by stakater-user** [comment]
@DhiaTN Yikes! You better fix it before anyone else finds out! [Build 7](https://jenkins.release.stakater.com/job/stakater/job/IngressMonitorController/job/PR-170/7/) has Failed!

**Comment by stakater-user** [comment]
@DhiaTN Image is available for testing. ``docker pull stakater/ingressmonitorcontroller:SNAPSHOT-PR-170-8``

**Comment by grebois** [comment]
```
time="2019-05-06T12:06:28Z" level=info msg="Error reading basic auth password from environment variable"
time="2019-05-06T12:06:29Z" level=info msg="Monitor couldn't be updated: sandbox-service-template-sandbox-service-template-service"
time="2019-05-06T12:06:29Z" level=info msg="No data has been updated (is any data different?)"```

**Comment by grebois** [comment]
@stakater-user you should update the version in the helm chart https://github.com/helm/charts/tree/master/stable/ingressmonitorcontroller

**Pull request merged**
